AWSTemplateFormatVersion: "2010-09-09"

# Outputs:
#   ChatQLApiId:
#     Description: Unique AWS AppSync GraphQL API Identifier
#     Value: !GetAtt chatQLApi.ApiId
#   ChatQLApiUrl:
#     Description: The Endpoint URL of your GraphQL API.
#     Value: !GetAtt chatQLApi.GraphQLUrl

Resources:
  usersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  awsAppSyncServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  dynamodbAccessPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "dynamodb-access"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "dynamodb:*"
            Resource:
              - !GetAtt usersTable.Arn
              # - !Sub "${userConversationsTable.Arn}/index/conversationId-index"
      Roles:
        - Ref: "awsAppSyncServiceRole"

  chatQLApi:
    Type: "AWS::AppSync::GraphQLApi"
    Properties:
      Name: "ChatQL"
      AuthenticationType: "API_KEY"

  usersTableDataSource:
    Type: "AWS::AppSync::DataSource"
    Properties:
      ApiId: !GetAtt chatQLApi.ApiId
      Name: "usersTableDataSource"
      Description: "usersTable DynamoDB data source"
      Type: "AMAZON_DYNAMODB"
      ServiceRoleArn: !GetAtt awsAppSyncServiceRole.Arn
      DynamoDBConfig:
        TableName: !Ref usersTable
        AwsRegion: !Ref "AWS::Region"

  chatQLSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt chatQLApi.ApiId
      Definition: |
        schema {
          query: Query
          mutation: Mutation
        }

        type Mutation {
          #  Put a single value of type 'User'. If an item does not exist with the same key the item will be created. If there exists an item at that key already, it will be updated.
          createUser(username: String!): User
        }

        type Query {
          #  Scan through all values of type 'User'. Use the 'after' and 'before' arguments with the 'nextToken' returned by the 'UserConnection' result to fetch pages.
          allUser(after: String, first: Int): [User]
          #  Get my user.
          me: User
        }

        type User {
          #  A unique identifier for the user.
          userId: ID!
          #  Generated id for a user. read-only
          id: ID!
          #  The username
          username: String!
          # is the user registered?
        	registered: Boolean
        }

  createUserMutationResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt chatQLApi.ApiId
      TypeName: "Mutation"
      FieldName: "createUser"
      DataSourceName: !GetAtt usersTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "PutItem",
          "attributeValues" : {
              "userId": {  "S": "${context.arguments.sub}" },
              "username": {  "S": "${context.arguments.username}" },
              "id": {  "S": "${context.arguments.sub}" },
              "registered": {  "BOOL": true }
          }
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result)

  allUserQueryResolver:
    Type: "AWS::AppSync::Resolver"
    Properties:
      ApiId: !GetAtt chatQLApi.ApiId
      TypeName: "Query"
      FieldName: "allUser"
      DataSourceName: !GetAtt usersTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version" : "2017-02-28",
          "operation" : "Scan",
          "limit": #if(${context.arguments.first}) "${context.arguments.first}" #else 20 #end,
          "nextToken": #if(${context.arguments.after}) "${context.arguments.after}" #else null #end
        }
      ResponseMappingTemplate: |
        $utils.toJson($context.result.items)
